# Header
menu:
  主页: /
  所有文章: /archives
  相册: /instagram
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/JoshPAT"
  weibo: "http://weibo.com/u/3503482562/home?wvr=5"
  facebook: "https://www.facebook.com/quan.zhou.102"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "https://en.gravatar.com/userimage/87177847/9f41bd8145e833e43ab4594f2bbd9c7c.jpg?size=200"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: joshpat
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我就是我，是不一样的烟火...
